######################################################################
##
## Filename: tb_ssp_wrap.udo
## Created on: Thu Nov 28 19:44:59 GMT Standard Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
## The format is specially for 16-bit integer ALU
######################################################################

add log -r *
delete wave *
add wave /tb_ssp_wrap/u_ssp/clk

add wave -noupdate -divider -height 32 "PC & ID"
add wave -radix unsigned /tb_ssp_wrap/u_ssp/u_core_0/u_pm/i_addr
add wave /tb_ssp_wrap/u_ssp/u_core_0/u_id/opc
add wave /tb_ssp_wrap/u_ssp/u_core_0/u_id/o_id_get0
add wave /tb_ssp_wrap/u_ssp/u_core_0/u_id/o_id_get_or_peak0
add wave /tb_ssp_wrap/u_ssp/u_core_0/u_id/o_id_fifowrite
add wave /tb_ssp_wrap/u_ssp/u_core_0/u_id/o_id_rdsm
add wave /tb_ssp_wrap/u_ssp/u_core_0/u_id/o_id_rddm0
add wave /tb_ssp_wrap/u_ssp/u_core_0/u_id/o_id_wrdm

#add wave -noupdate -divider -height 32 "RF signals"
#add wave  /tb_ssp_wrap/u_ssp/u_core_0/rf_gen/v_rf_gen(0)/u_rf/i_wen
#add wave -radix unsigned /tb_ssp_wrap/u_ssp/u_core_0/rf_gen/v_rf_gen(0)/u_rf/i_wraddr_d
#add wave -radix decimal /tb_ssp_wrap/u_ssp/u_core_0/rf_gen/v_rf_gen(0)/u_rf/i_wrdata_d

add wave -noupdate -divider -height 32 "DSP48E signals"
add wave /tb_ssp_wrap/u_ssp/u_core_0/DSP48_GEN/v_ex_gen(0)/u_ex/i_src_a
add wave /tb_ssp_wrap/u_ssp/u_core_0/DSP48_GEN/v_ex_gen(0)/u_ex/i_src_b
add wave /tb_ssp_wrap/u_ssp/u_core_0/DSP48_GEN/v_ex_gen(0)/u_ex/i_src_c
add wave /tb_ssp_wrap/u_ssp/u_core_0/v_wb_gen(0)/u_wb/i_alusra
add wave /tb_ssp_wrap/u_ssp/u_core_0/v_wb_gen(0)/u_wb/i_dsp48sra_result

add wave -noupdate -divider -height 32 "Input FIFO"
add wave /tb_ssp_wrap/u_ssp/u_core_0/id_get_inst0_Pb2(0)
add wave /tb_ssp_wrap/u_ssp/u_fifo_IOCore_to_SPU0PE0/o_data

add wave -noupdate -divider -height 32 "Output FIFO"
add wave /tb_ssp_wrap/u_ssp/u_fifo_SPU4PE0_to_IOCore/write
add wave /tb_ssp_wrap/u_ssp/u_fifo_SPU4PE0_to_IOCore/i_data

add wave -noupdate -divider -height 32 "Your signals"

