# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xcku9p-ffve900-3-e-EVAL

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/sfpe/projects/sFPE_basic_test/sFPE_basic_test.cache/wt [current_project]
set_property parent.project_path D:/sfpe/projects/sFPE_basic_test/sFPE_basic_test.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_mem {
  D:/sfpe/source/firmware/sFPE/subCompontents/sFPE_SM/init0.mif
  D:/sfpe/source/firmware/sFPE/subCompontents/sFPE_PM/init0.mif
  D:/sfpe/source/firmware/sFPE/subCompontents/sFPE_DM/init0.mif
}
read_vhdl -library xil_defaultlib {
  D:/sfpe/source/firmware/sFPE/sFPE_typedef.vhd
  D:/sfpe/source/firmware/generic_registers/generic_registers.vhd
  D:/sfpe/source/firmware/sFPE/subCompontents/sFPE_ID/sFPE_inst_encoding.vhd
  D:/sfpe/source/firmware/generic_multiplexers/generic_multiplexers.vhd
  D:/sfpe/source/firmware/sFPE/subCompontents/sFPE_wrtie_back/spu_writeback.vhd
  D:/sfpe/source/firmware/sFPE/subCompontents/sFPE_SM/sFPE_SM.vhd
  D:/sfpe/source/firmware/sFPE/subCompontents/sFPE_SAU/sFPE_SAU.vhd
  D:/sfpe/source/firmware/sFPE/subCompontents/sFPE_RF/sFPE_RF.vhd
  D:/sfpe/source/firmware/sFPE/subCompontents/sFPE_EX/sFPE_EX.vhd
  D:/sfpe/source/firmware/sFPE/subCompontents/sFPE_DM/sFPE_DM.vhd
  D:/sfpe/source/firmware/sFPE/subCompontents/sFPE_comm_put/sFPE_comm_put.vhd
  D:/sfpe/source/firmware/sFPE/subCompontents/sFPE_PM/sFPE_PM.vhd
  D:/sfpe/source/firmware/sFPE/subCompontents/sFPE_PC/sFPE_PC.vhd
  D:/sfpe/source/firmware/sFPE/subCompontents/sFPE_ID/sFPE_ID.vhd
  D:/sfpe/source/firmware/sFPE/subCompontents/sFPE_comm_get/sFPE_comm_get.vhd
  D:/sfpe/source/firmware/sFPE/subCompontents/sFPE_branch/sFPE_branch.vhd
  D:/sfpe/source/firmware/sFPE/sFPE.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top sFPE -part xcku9p-ffve900-3-e-EVAL


write_checkpoint -force -noxdef sFPE.dcp

catch { report_utilization -file sFPE_utilization_synth.rpt -pb sFPE_utilization_synth.pb }
