# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbg484-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/sfpe/projects/generated_VHDL_testing/enerated_VHDL_testing.cache/wt [current_project]
set_property parent.project_path D:/sfpe/projects/generated_VHDL_testing/enerated_VHDL_testing.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -vhdl2008 -library xil_defaultlib {
  D:/sfpe/projects/generated_VHDL_testing/src/demux_4.vhd
  D:/sfpe/projects/generated_VHDL_testing/src/mux_4.vhd
  D:/sfpe/projects/generated_VHDL_testing/src/reg_FFEA.vhd
  D:/sfpe/projects/generated_VHDL_testing/src/reg_TFEA.vhd
  D:/sfpe/projects/generated_VHDL_testing/src/test_prog_mem.vhd
  D:/sfpe/projects/generated_VHDL_testing/src/test_IMM.vhd
  D:/sfpe/projects/generated_VHDL_testing/src/test_data_mem.vhd
  D:/sfpe/projects/generated_VHDL_testing/src/test_instr_decoder.vhd
  D:/sfpe/projects/generated_VHDL_testing/src/test_delay.vhd
  D:/sfpe/projects/generated_VHDL_testing/src/test_comm_get.vhd
  D:/sfpe/projects/generated_VHDL_testing/src/test_status_reg.vhd
  D:/sfpe/projects/generated_VHDL_testing/src/test_reg_file.vhd
  D:/sfpe/projects/generated_VHDL_testing/src/test_prog_counter.vhd
  D:/sfpe/projects/generated_VHDL_testing/src/test_comm_put.vhd
  D:/sfpe/projects/generated_VHDL_testing/src/test_ALU.vhd
  D:/sfpe/projects/generated_VHDL_testing/src/priority_mux_4.vhd
  D:/sfpe/projects/generated_VHDL_testing/src/priority_mux_3.vhd
  D:/sfpe/projects/generated_VHDL_testing/src/test.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top test -part xc7k70tfbg484-3


write_checkpoint -force -noxdef test.dcp

catch { report_utilization -file test_utilization_synth.rpt -pb test_utilization_synth.pb }
