######################################################################
##
## Filename: tb_ssp_top.udo
## Created on: Fri Jan 10 13:39:21 GMT Standard Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
